#--------------------------------------------------------------------------------
# Stage 1: Build TypeScript (ใช้ Node สร้างโค้ด TypeScript ให้เป็น JavaScript ใน dist/)
#--------------------------------------------------------------------------------
# กำหนดให้ใช้ Node.js เวอร์ชัน 22 บน Alpine Linux เป็น Base Image
# ตั้งชื่อ Stage นี้ว่า builder
FROM node:22-alpine AS builder

# ตั้งค่าไดเร็กทอรีทำงานภายในคอนเทนเนอร์เป็น /app
WORKDIR /app

# คัดลอกไฟล์ package.json และ package-lock.json มา
COPY package*.json ./
# ติดตั้ง Dependencies ทั้งหมด ที่ระบุใน package.json
RUN npm install

# คัดลอก Source Code TypeScript ทั้งหมดเข้าไปในคอนเทนเนอร์
COPY . .

# รันคำสั่ง Build ที่ระบุใน package.json เพื่อแปลง TypeScript เป็น JavaScript
RUN npm run build

#----------------------------------------------------------
# Stage 2: Run built files (ใช้ container ใหม่เพื่อรันโปรเจกต์จริง)
#----------------------------------------------------------
# ใช้ Base Image ตัวเดิม
FROM node:22-alpine
# ตั้งค่าไดเร็กทอรีทำงานเป็น /app
WORKDIR /app

# คัดลอกเฉพาะโฟลเดอร์ dist (ที่มีไฟล์ JavaScript ที่คอมไพล์แล้ว) จาก Stage ชื่อ builder มาไว้ที่ /app/dist ใน Stage ปัจจุบัน
COPY --from=builder /app/dist ./dist
# คัดลอกไฟล์ package*.json มาอีกรอบ
COPY package*.json ./

# ตั้ง Dependencies ที่จำเป็นสำหรับการรันเท่านั้น
RUN npm install --omit=dev

#ใช้พอร์ต 4000
EXPOSE 4000

# คำสั่งที่จะ รันแอปพลิเคชัน เมื่อคอนเทนเนอร์เริ่มต้น โดยการเรียกใช้ไฟล์ JavaScript หลักที่ถูก Build แล้ว
CMD ["node", "dist/server.js"]
